apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abdulrahmanalaa123/DEVOPS_CAPSTONE.git
    targetRevision: eks_module
    path: argocd-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true